name: HardcoreTweaks
main: Hardcore.HCTweaks
author: EvModder/EvDoc/Evil_Witchdoctor
version: 1.2 #1.2=spectator system upgrades
softdepend: [Essentials, HorseOwners] # Horse(ClaimEvent,RenameEvent) used in ScoreboardManager
api-version: 1.13

commands:
   about:
      description: View information about a player
      usage: /about <name>
      aliases: [seen,info]
      permission: hardcore.about
      permission-message: You do not have permission to do this.

   autoquit:
      description: Set up AutoQuit when your health falls below a threshold
      usage: /autoquit #
      aliases: [autodisconnect,autoleave]
      permission: hardcore.autoquit
      permission-message: You do not have permission to do this.

   color:
      description: Change the color of your name in chat
      usage: /color c
      aliases: [cl,format,colour,namecolor,namecolour,cnick]
      permission: hardcore.color
      permission-message: You do not have permission to do this.

   deathlog:
      description: View the last 9 deaths
      usage: /deathlog
      aliases: [deaths,deathslog,deathlogs]
      permission: hardcore.deathlog
      permission-message: You do not have permission to do this.

   showscores:
      description: View the current contest scoreboard
      usage: /levels
      aliases: [levels,level,lvls,lvl,sb,scores,xptop,topscore,topscores,xplevels]
      permission: hardcore.showscores
      permission-message: You do not have permission to do this.

   spectate:
      description: Configure spectator settings
      usage: /spec [mode] <blacklist/whitelist> [name]
      aliases: [sp,spec,spectators]
      permission: hardcore.spectateconfig
      permission-message: You do not have permission to do this.

   whitelist:
      description: Display or edit your spectator whitelist
      usage: /whitelist [add/remove] [name]
      aliases: [wl]
      permission: hardcore.spectateconfig
      permission-message: You do not have permission to do this.

   blacklist:
      description: Display or edit your spectator blacklist
      usage: /blacklist [add/remove] [name]
      aliases: [bl]
      permission: hardcore.spectateconfig
      permission-message: You do not have permission to do this.

   tpa:
      description: Request to teleport to the specified player
      usage: /tpa <name>
      aliases: [htpa]
      permission: hardcore.tpa
      permission-message: You do not have permission to do this.

   tpahere:
      description: Request that the specified player teleport to you
      usage: /tpa <name>
      aliases: [htpahere]
      permission: hardcore.tpahere
      permission-message: You do not have permission to do this.

   tpaccept:
      description: Accepts teleport request from the specified player
      usage: /tpaccept <name>
      aliases: [htpaccept]
      permission: hardcore.tpaccept
      permission-message: You do not have permission to do this.

   regioncleanup:
      description: Delete region files that match given criteria
      usage: /regioncleanup [world:<name>/all] [visitlog:true/false]m [age:2m10d45m] [size:XXXX (in KB)] [mock]
      permission: hardcore.regiondelete
      permission-message: You do not have permission to do this.

permissions:
   hardcore.about:
      description: Permission to use /about
      default: true

   hardcore.autoquit:
      description: Permission to use /autoquit
      default: true

   hardcore.color:
      description: Permission to use /color
      default: true

   hardcore.compass.coords:
      description: Tell coordinates when using a compass tracker
      default: op

   hardcore.compass.coords.approximate:
      description: Tell approximate coordinates when using a compass tracker
      default: true

   hardcore.seen:
      description: Permission to use /seen
      default: true

   hardcore.deathlog:
      description: Permission to use /deathlog
      default: true

   hardcore.showscores:
      description: Permission to use /showscores
      default: op

   hardcore.spectateconfig:
      description: Permission to use /spectate
      default: true

   hardcore.teleport.override:
      description: Prevents plugin from canceling teleports
      default: op

   hardcore.tpa:
      description: Permission to use /tpa <name>
      default: true

   hardcore.tpahere:
      description: Permission to use /tpahere <name>
      default: true

   hardcore.tpaccept:
      description: Permission to use /tpaccept <name>
      default: true

   hardcore.regiondelete:
      description: Permission to use /regioncleanup
      default: op

   hardcore.novisitlog:
      description: Do not add this player to .visitlog files
      default: false

   hardcore.spectator.bypass.tpcheck:
      description: Bypass check for valid target at destination when teleporting as a spectator
      default: op

   hardcore.spectator.bypass.blindness:
      description: Prevents a spectator from being given blindness
      default: op

   hardcore.spectator.bypass.slowness:
      description: Prevents a spectator from being given slowness
      default: op

   hardcore.spectator.bypass.forcedtarget:
      description: Prevents a spectator from being forced to spectate from a player's POV
      default: op

   hardcore.spectator.bypass.maxrange:
      description: Prevents a spectator from being forced to remain within a radius of an alive player
      default: op

   hardcore.spectator.bypass.antixray:
      description: Prevents a spectator from being forced stay in an air block
      default: op

   hardcore.spectator.bypass.antixray.ifclose:
      description: Prevents a spectator from being forced stay in an air block IF they are close to the target player
      default: op

   hardcore.spectator.bypass.notify:
      description: Hides notifications to players that you are spectating them
      default: op